version: '3'
services:
  app-manager:
    container_name: app-manager
    ports:
      - "8080:8080"
      - "8443:443"
    secrets:
      - source: firebase-service-account
        target: /mnt/data/cert/firebase-service-account.json
    volumes:
      - type: bind
        source: ./config.properties
        target: /config.properties
